apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: discovery-operator-metrics
  # the service monitor has to be in the OCP Prometheus namespace
  namespace: openshift-monitoring
spec:
  endpoints:
  - port: web
    interval: 30s
  namespaceSelector:
    matchNames:
    - open-cluster-management
  selector:
    matchLabels:
      app: discovery-operator